### ISSUE TITLE
Connection Lost, Can't Reconnect

### ISSUE THREAD

**Issue by mrichardson23** [ekulyk/PythonPusherClient#2]
After a few minutes of not receiving data, I see in the console:

Did not receive any data in time.  Reconnecting.
Connection: Error - [Errno 35] Resource temporarily unavailable
Connection: Connection closed
Attempting to connect again in 10 seconds.
Connection: Connection opened
Connection: Connection closed
Attempting to connect again in 10 seconds.

The API documentation says: "In protocol versions 5 and above, when using an old version of the WebSocket protocol, Pusher will send pusher:ping event (see events) to the client. The client should respond with a pusher:pong event." I don't see any ping events coming through, though.

**Comment by ekulyk** [comment]
I just ran the basic example to see what would happen after leaving the connection idle for 5 minutes.  I didn't see a pusher:ping event, but I did see a pusher:heartbeat event make it through.  My connection stayed open due to the heartbeat.  I was able to receive messages sent to the subscribed channel via the Pusher Event page.

I haven't used this code since they've added the pusher:ping and pusher:pong messages.  I noticed as well that they've added a protocol version argument that can be supplied as part of the URL.  The python client masquerades as an old javascript client so I imagine Pusher would infer the correct protocol version to use.

Are you able to get any messages through to the client?  Can you see the connection and channel subscription taking place on the pusher debug page?

**Comment by mrichardson23** [comment]
Thanks for the reply. I monkeyed around with your source code a lot and used protocol=5 as part of the URL. I had my Python app sending a ping to the server ever 120 seconds and that would keep the connection open MUCH longer. However, I need my Python app to be able to run for days on end without user intervention and of course an occasional disconnect is inevitable. I found that eventually, when it does get disconnected, it still can't seem to reconnect (but it does connect and then disconnect immediately... see below).

I downloaded and installed this library fresh and ran the basic.py example with my app key. I let the connection go idle (not sending any events). I didn't see any messages come through on the client side. After five minutes I see:

Did not receive any data in time.  Reconnecting.
Connection: Connection closed
Attempting to connect again in 10 seconds.
Connection: Connection opened
Connection: Connection closed
Attempting to connect again in 10 seconds.
Connection: Connection opened
Connection: Connection closed
Attempting to connect again in 10 seconds.

On my debug console on Pusher (great thinking to check there!), I see the connection, then the disconnection immediately after. So there is indeed a connection being made there, but it's immediately closed.

By the way, thank you so much for the work you've done on the library and for helping out with this issue.

**Comment by ekulyk** [comment]
I think I can reproduce your problem.  It seems to happen when I use the latest websocket-client from https://github.com/liris/websocket-client.  I will look into what is causing this issue.

In the mean time, use an old version of websocket-client which includes a small patch that fixes URL query params: https://github.com/ekulyk/websocket-client.

I will update the readme to point to the version I've used until I can figure out what is happening with the latest.

**Comment by mrichardson23** [comment]
Thanks, this works wonderfully. I see the hearbeats now and I can even physically disconnect my machine from the network and it will recover when I reconnect it. Thanks so much for looking into this.

**Comment by ekulyk** [comment]
Has been fixed thanks to this guy:
https://github.com/fuzeman/PythonPusherClient/commit/31ae459fc8e013ccaae074c87336dd393d664c34
