### ISSUE TITLE
Add tests!

### ISSUE THREAD

**Issue by WestleyArgentum** [ekulyk/PythonPusherClient#20]
Adding tests and hooking up something like travis would be really helpful!

**Comment by ekulyk** [comment]
Yeah, for sure!  I had never heard of Travis before - looks like it would work well for this.  Maybe if work lets up I'll look at showing this project some love and fleshing out some tests.

**Comment by aalex** [comment]
You will need a fake server for writing system tests. That might be tricky. For unit tests, it will be a bit easier at first, at least.

**Comment by ekulyk** [comment]
Added basic connect/message receive test by creating a mock pusher server using Autobahn ws.  Also tests reconnect functionality.

Integrated with travis ci and added a build badge to the readme.  Currently failing on Python 3.2 due to syntax error in the autobahn library, but otherwise passing 2.6, 2.7, 3.3, 3.4.

No private/presence channel testing and could use some more unit tests, but should catch some basic communications issues.
